services:
  garage1:
    image: dxflrs/garage:v2.3.0
    container_name: garage
    hostname: garage
    restart: unless-stopped
    ports:
      - "3900:3900" # API S3 acessível pela sua App
      - "3902:3902" # Console WEB
      - "3903:3903" # Admin API
    volumes:
      - ./data:/var/lib/garage
      - ./garage.toml:/etc/garage.toml
    environment:
      - GARAGE_CONFIG=/etc/garage.toml
      - GARAGE_RPC_SECRET=${GARAGE_RPC_SECRET}
      - GARAGE_ADMIN_TOKEN=${GARAGE_ADMIN_TOKEN}
      - GARAGE_METRICS_TOKEN=${GARAGE_METRICS_TOKEN}
