services:
  kafka:
    image: apache/kafka:4.2.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092" # Porta do KAFKA
      - "9094:9094" # Porta que o servidor e os processadores vão usar
    environment:
      # Configurações do KRaft
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        # Diz para o Kafka que o tópico de offsets pode ter apenas 1 cópia (já que só temos 1 container)
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  
      # Faz o mesmo para os tópicos de estado interno de transações (bom para evitar erros futuros)
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1

      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka
    # Interface visual opcional para ver as mensagens e tópicos

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8084:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    
volumes:
 kafka_data: